# Logitech Attack3
axis_linear: 3  # Forward/Back
scale_linear: 0.1
scale_linear_turbo: 0.4

axis_angular: 0  # Left/Right
scale_angular: 0.5

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
